### ISSUE TITLE
Android P deprecation, Invalid Region.Op

### ISSUE THREAD

**Issue by alashow** [zagum/Android-SwitchIcon#11]
Library crashes on Android P:
```
java.lang.IllegalArgumentException: Invalid Region.Op - only INTERSECT and DIFFERENCE are allowed
        at android.graphics.Canvas.checkValidClipOp(Canvas.java:779)
        at android.graphics.Canvas.clipPath(Canvas.java:1007)
        at com.github.zagum.switchicon.SwitchIconView.onDraw(SwitchIconView.java:211)
```

https://developer.android.com/reference/android/graphics/Canvas#clipPath(android.graphics.Path,%20android.graphics.Region.Op)

**Comment by zagum** [comment]
Thx, fix added in v 1.3.8
