### ISSUE TITLE
Android Studio Preview rendering: NullPointerException

### ISSUE THREAD

**Issue by natnayr** [zagum/Android-SwitchIcon#4]
Hi, i'm getting the following android studio preview error:

```
java.lang.NullPointerException
	at sun.java2d.SunGraphics2D.getClipBounds(SunGraphics2D.java:1831)
	at sun.java2d.SunGraphics2D.getClipBounds(SunGraphics2D.java:1818)
	at com.android.layoutlib.bridge.impl.GcSnapshot.drawInLayer(GcSnapshot.java:623)
	at com.android.layoutlib.bridge.impl.GcSnapshot.draw(GcSnapshot.java:583)
	at android.graphics.Canvas_Delegate.draw(Canvas_Delegate.java:1032)
	at android.graphics.Canvas_Delegate.native_drawPath(Canvas_Delegate.java:713)
	at android.graphics.drawable.VectorDrawable_Delegate$VPathRenderer_Delegate.drawPath(VectorDrawable_Delegate.java:1200)
	at android.graphics.drawable.VectorDrawable_Delegate$VPathRenderer_Delegate.drawGroupTree(VectorDrawable_Delegate.java:1121)
	at android.graphics.drawable.VectorDrawable_Delegate$VPathRenderer_Delegate.draw(VectorDrawable_Delegate.java:1129)
	at android.graphics.drawable.VectorDrawable_Delegate.nDraw(VectorDrawable_Delegate.java:156)
	at android.graphics.drawable.VectorDrawable.nDraw(VectorDrawable.java)
	at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:307)
	at android.widget.ImageView.onDraw(ImageView.java:1286)
	at com.github.zagum.switchicon.SwitchIconView.onDraw_Original(SwitchIconView.java:211)
	at com.github.zagum.switchicon.SwitchIconView.onDraw(SwitchIconView.java)
	at android.view.View.draw(View.java:17068)
	at android.view.View.draw(View.java:16976)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:16974)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:16974)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17071)
	at android.view.View.draw(View.java:16976)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:16974)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:16974)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:16974)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
	at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
	at android.view.View.draw(View.java:17071)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:394)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:505)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:87)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:154)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:136)
	at com.android.tools.idea.rendering.RenderTask.lambda$renderInner$71(RenderTask.java:698)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by zagum** [comment]
Can you show me your layout xml and vector xml?

**Comment by zagum** [comment]
Not enough info. Can't reproduce
